default: &default
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: fotbot
  password: tobtof

development:
  <<: *default
  database: fotbot_dev

test:
  <<: *default
  database: fotbot_test
